data: 
  data_dir: "dataSetsAll"

trainer:
  num_train_epochs: 10
  seed: 202412
  output_dir: "exp/"
  optim: adam
  dataloader_num_workers: 4
  per_device_train_batch_size: 64
  eval_batch_size: 128
  learning_rate: 0.001
  lr_scheduler_type: cosine_with_min_lr_schedule_with_warmup
  warmup_ratio: 0.0
  warmup_steps: 1000
  cosine_with_min_lr_schedule_with_warmup_num_cycles: 0.5
  cosine_with_min_lr_schedule_with_warmup_initial_lr: 0.001
  cosine_with_min_lr_schedule_with_warmup_min_lr: 0.0001
  metric_for_best_model: "test_accuracy"

model:
  network:
    num_hidden_layers: 3
    num_hidden_units: [64, 256, 128]
    recurrent_layer: [0, 1]

  neuron:
    surrogate_gradient: "atan"
    reset: "hard"
    tau: 2.
    v_threshold: 1.