data: 
  dataset: "gsc"
  batch_size: 128
  num_workers: 4
  aug: True
  version: 1
  if_command: True
  if_spk: False  # for SHD

trainer:
  num_train_epochs: 100
  seed: 202412
  device: "cuda:0"
  output_dir: "exp/"
  optimizer: 
    type: "adam"
    params:
      learning_rate: 0.001
  scheduler:
    type: "step"
    params: 
      step_size: 30
      gamma: 0.1

model:
  network:
    num_hidden_layers: 3
    num_hidden_units: [64, 256, 128]
    recurrent_layer: [0, 1]

  neuron:
    surrogate_gradient: "atan"
    reset: "hard"
    tau: 2.
    v_threshold: 1.