data: 
  dataset: "ssc"
  aug: False
  version: 1
  if_command: True
  if_spk: True


trainer:
  num_train_epochs: 100
  seed: 202412
  output_dir: "exp/"
  optim: adam
  dataloader_num_workers: 4
  per_device_train_batch_size: 128
  eval_batch_size: 128
  learning_rate: 0.001
  lr_scheduler_type: cosine_with_min_lr_schedule_with_warmup
  warmup_ratio: 0.0
  warmup_steps: 1000
  cosine_with_min_lr_schedule_with_warmup_num_cycles: 0.5
  cosine_with_min_lr_schedule_with_warmup_initial_lr: 0.001
  cosine_with_min_lr_schedule_with_warmup_min_lr: 0.0001
  metric_for_best_model: "test_accuracy"

model:
  network:
    num_hidden_layers: 2
    num_hidden_units: [128, 128]
    recurrent_layer: [0, 1]

  neuron:
    neuron_class: "Recurrent_LIF"
    args:
      rest: 0.0
      decay: 0.8
      threshold: 1.0
      exec_mode: "serial"
      surro_grad: "triangle"  # Example surrogate gradient
