data: 
  dataset: "gsc"
  aug: False
  version: 2
  if_command: True
  if_spk: False

trainer:
  num_train_epochs: 100
  seed: 202412
  output_dir: "exp/"
  optim: adam
  dataloader_num_workers: 4
  per_device_train_batch_size: 256
  eval_batch_size: 64
  learning_rate: 0.001
  lr_scheduler_type: cosine_with_min_lr_schedule_with_warmup
  warmup_ratio: 0.0
  warmup_steps: 1000
  cosine_with_min_lr_schedule_with_warmup_num_cycles: 0.5
  cosine_with_min_lr_schedule_with_warmup_initial_lr: 0.001
  cosine_with_min_lr_schedule_with_warmup_min_lr: 0.0001
  metric_for_best_model: "test_accuracy"


model:
  model_name: "spikingnet"
  input_size: 40
  hidden_size: 300
  output_size: 14
  num_layers: 3
  dropout: 0.0
  neuron_type: "clif"
  bidirectional: False
  batch_first: True
  neuron_args:
    rest: 0.0
    decay: 0.5
    threshold: 0.5
    exec_mode: "serial"
    recurrent: True
  SG_args:
    SG_class: "triangle"
    alpha: 0.6
